### ISSUE TITLE
"Save" has no effect on existing file

### ISSUE THREAD

**Issue by lzambarda** [kohii/smoothcsv3#4] opened 2024-11-01 15:42 UTC
If I open an existing file and modify it, I can't seem to be able to save it using "Save" or its shortcut. However, if I use "Save As" this works fine.

This seems to be working fine if I create a new file and save it.

**Comment by kohii** [comment] 2024-11-03 04:24
Thank you for reporting this issue.

I tried to reproduce the problem but couldn't replicate it. Here are the steps I took:

1. Opened an existing CSV file by dragging and dropping it into SmoothCSV (UTF-8 encoding).
2. Edited a cell in the opened file.
3. Saved the file using `cmd+s` or by selecting **File > Save** from the menu bar.

If there's anything I might be misunderstanding or if you're following different steps, please let me know so I can investigate further.

**Comment by lzambarda** [comment] 2024-11-04 09:48
I have tried with your steps and they work fine for me too, therefore here are the steps I can use to reliably replicate the issue:

1. Have SmoothCSV closed.
2. Open a CSV file by double-clicking.
3. Edit a cell in the opened file.
4. Saving, with either aforementioned method, should not work.

Hopefully this can help you to shed some light on this.

**Comment by kohii** [comment] 2024-11-09 02:40
I was able to reproduce the issue with the steps you provided and have identified the cause of the problem.
This issue will be fixed in the next release.

Thank you for your help in identifying the problem.

**Comment by kohii** [comment] 2024-11-13 10:25
This bug is fixed in the latest release!
https://github.com/kohii/smoothcsv3/releases/tag/v3.0.0-beta.1

**Closed by kohii** 2024-11-13 10:25 UTC
